#!/bin/bash
export TARGET_PROJECTS=(
	":jar-searcher"
	":asm-tools"
	":jenkins-tools"
)

__gradle_exec(){
	./gradlew "${@}";
}

__rp_deploy_project(){
	echo ">>> ${1} <<<" && sh release "${1}"
}

rp_deploy() {
   __gradle_exec ':base-tool-lib:clean' ':base-tool-lib:release'
   echo ":base-tool-lib:clean" ":base-tool-lib:release"
   for p in "${TARGET_PROJECTS[@]}"; do __rp_deploy_project "${p}"; done
}

rp_deploy